Vagrant.configure("2") do |config|
    config.vm.define "web" do |web|
        web.vm.box = "ubuntu/bionic64"
        web.vm.network "private_network", ip: "192.168.50.3"
    end

    config.vm.define "zabbix" do |zabbix|
        zabbix.vm.box = "ubuntu/bionic64"
        zabbix.vm.network "private_network", ip: "192.168.50.4"
        zabbix.vm.provider "virtualbox" do |v|
            v.memory = 4096
        end
    end
end
